#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: MIT
# Consolidated ProtonVPN service: one procd-supervised ucode daemon that
# refreshes the server-list cache, renews the session/certificate and runs
# scheduled rotation. The daemon reads /etc/config/protonvpn and re-reads it
# on every tick; the reload trigger restarts it when the config changes.

START=99
USE_PROCD=1

EXTRA_COMMANDS="version"
EXTRA_HELP="	version         Show the installed protonvpn-wireguard version"

version() {
	ucode -e 'print(require("protonvpn.common").VERSION, "\n");' 2>/dev/null
}

start_service() {
	procd_open_instance protonvpn
	procd_set_param command /usr/bin/protonvpn-service
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "protonvpn"
}

reload_service() {
	stop
	start
}
